---
abstract: 'Parses datetime strings from the Salesforce API'
author:
  - 'Carl Vincent <carl.vincent@netskills.ac.uk>'
build_requires: {}
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Format-Salesforce
provides:
  DateTime::Format::Salesforce:
    file: lib/DateTime/Format/Salesforce.pm
    version: 0.01_01
recommends:
  File::Find::Rule: 0.24
  Test::Distribution: 1.22
  Test::Pod: 0.95
requires:
  DateTime: 0.18
  DateTime::Format::Builder: 0.77
resources:
  license: http://dev.perl.org/licenses/
  repository: 
    url: git://github.com/carlvincent/DateTime-Format-Salesforce.git
    web: https://github.com/carlvincent/DateTime-Format-Salesforce
    type: git
version: 0.01_01
